name: frontend-deploy
on: 
  push:
    branches: [ master ]
jobs:
  frontend-deploy:
    runs-on: self-hosted2
    steps:
      - uses: actions/checkout@v2

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: remove
        run: rm -rf ./*
        working-directory: /usr/share/nginx/blog-front/

      - name: cp
        run: cp -r ./public/* /usr/share/nginx/blog-front/
